### ISSUE TITLE
Support for multilevel path filter operations

### ISSUE THREAD

**Issue by JustinDanielson** [COVESA/vehicle-information-service-specification#21]
## **Premise:**
I want to write code to check the tire pressure of all tires, and potentially in vehicles such as dual rear wheel trucks. I don't know how that spec will be implemented in the future.

All tire's pressures can be returned with

```
{
    "action": "get",
    "path": "Vehicle.Chassis.Axle",
    "filter": {"variant": "paths", "parameter": ["#.Tire.Pressure"]}  //assuming '#' is multilevel wildcard
}
```

alternatively, we could supply another parameter to the filter

```
    "filter": {"variant": "paths", "parameter": ["*.Tire.Pressure"], "multilevel": true}
```

## **Challenge:**
Current path filter requires me to know that the path has many instances and where they are within the path string.

If the implementation follows the sample vspec(below), then I cannot do the following filter because my paths in the front and rear tires are of different lengths.

```
{
    "action": "get",
    "path": "Vehicle.Chassis.Axle",
    "filter": {"variant":"paths", "parameter":["*.*.*.*.Tire.Pressure"]},
}
```

Do I include a second filter parameter? `"*.*.*.*.*.*.Tire.Pressure"` This is really getting ugly 😅

Assumed front tire path: `Axle.Row1.Wheel.Left.Tire.Pressure`
Assumed rear tire path: `Axle.Row2.Wheel.Left.Inside.Tire.Pressure`

Assumption of vspec implementation. (this may be incorrect?)

```
Axle:
  instances:
    - Row[1,2]
  type: branch
  description: Axle signals

Axle.Wheel:
  instances: ["Left","Right"]
  type: branch
  description: Wheel signals for axle

Axle.Row2.Wheel.Left:
  instances: ["Inside", "Outside"]
  type: branch
  description: Wheel signals for dual wheel axle
```
